### ISSUE TITLE
Modularize components

### ISSUE THREAD

**Issue by mattrasband** [pyslackers/ansible#19]
We have a number of redundancies, specifically across the sirbot and website. These should be made to be generic roles so we can make a playbook for each service instead of treating a service as a role.

For example, getting toward something like this:

```
roles
|
- nginx: Configure nginx for handling a domain, including SSL if a param is set
- python_service: Configure a virtualenv for an application that is cloned fresh
- flask_app: Create a basic service file that fires up our defaults for a site (gunicorn, runs flask migrate if a database is present, etc)
- asyncio_app: Create a basic service file that fires up the defaults for an async app (maybe this can just be a web_service and combined with flask_app)
```

**Comment by m1yag1** [comment]
Agreed. Inside the setup-server role ntp and fail2ban could become their own roles. Perhaps, we should go through and identify the ones to break up for separate issues?

**Comment by mikefromit** [comment]
Ok, let's try this again.. hehe. It may be good to identify the ones that need to be broken up. For example there is the setup-server playbook where fail2ban can become its own role as well as ntp.

**Comment by ovv** [comment]
> python_service: Configure a virtualenv for an application that is cloned fresh

It should also check and update requirements if necessary

Not sure about splitting the setup-server into a lot of small roles like fail2ban, ntp, ... it might become a bit harder to maintain and IMO the goal of this role is to be easily shareable between servers. I can't imagine a server where we wouldn't want ntp or fail2ban.

But I agree for the services roles.

**Comment by mattrasband** [comment]
Agreed @ovv - I think we should bundle the common things together (fail2ban, ufw, ssh config, ntp) and then have other roles for things like nginx, python, docker (if we ever decide to use that), etc.
